baseURL = "https://kevintheivendran.com/"
languageCode = "en-us"
title = "Kevin Theivendran"
theme = "hugo-theme-console"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1

[[menu.main]]
name = "Essays"
url = "/essays/"
weight = 2

[[menu.main]]
name = "Content"
url = "/content/"
weight = 3

